cerr_curate_app/cerr_curate_app/urls.py
from django.urls import include, path
from django.contrib import admin

from .views.user import draft
from .views.user import ajax as user_ajax

app_name = "draft"
urlpatterns = [
    path("draft/edit/ajax_get_role", user_ajax.role_form, name="ajax_get_role"),
    path("admin/", admin.site.urls),
    path("draft/start/", draft.start, name="start"),
    path("draft/edit/<str:draft_id>", draft.EditView.as_view(), name="edit"),
]

cerr_curate_app/createrec/urls.py
from django.urls import path

from . import views

app_name = 'createrec'
urlpatterns = [
    path('', views.start, name='index'),
    path('start', views.start, name='start'),
]

cerr_curate_app/urls.py
from django.urls import re_path
from cerr_curate_app.views.user import views as user_cerr_views, ajax as ajax

urlpatterns = [
    re_path(r"^$", user_cerr_views.get_name, name="core_curate_index"),

]

cerr_curate_app/cerr_curate_app/views/user/forms/start.py
"""
a module defining Forms used to start a draft record
"""
import os, pdb
from collections import OrderedDict
from collections.abc import Mapping

from django import forms as forms
from django.utils.html import conditional_escape
from django.forms.utils import ErrorDict

from .base import ComposableForm, MultiForm, CerrErrorList
from .selectrestype import ResourceTypeChoiceField

__all__ = "CreateForm StartForm".split()

TMPL8S = "cerr_curate_app/user/forms/"


class CreateForm(ComposableForm):
    """
    A Form for creating an initial draft of a record.

    It includes:
     * a text field for entering a mnemonic name
     * a URL field for entering the resource's landing page
     * an array of radio buttons for selecting a type
    """

    template_name = TMPL8S + "createform.html"
    name = forms.CharField(required=True)
    homepage = forms.URLField(required=False)
    scrape = forms.BooleanField(initial=True, required=False)
    restype = ResourceTypeChoiceField()

    def __init__(self, data=None, files=None, is_top=True, show_errors=None, **kwargs):
        self.is_top = is_top
        self.show_aggregate_errors = show_errors
        self.disabled = False
        if self.show_aggregate_errors is None:
            self.show_aggregate_errors = self.is_top
        if "error_class" not in kwargs:
            kwargs["error_class"] = CerrErrorList
        super(CreateForm, self).__init__(data, files, **kwargs)

    @property
    def name_errors(self):
        """
        return the errors associated with the name input
        """
        return self.errors.get("name", self.error_class(error_class="errorlist"))

    @property
    def homepage_errors(self):
        """
        return the errors associated with the homepage input
        """
        return self.errors.get("homepage", self.error_class(error_class="errorlist"))

    @property
    def restype_errors(self):
        """
        return the errors associated with the homepage input
        """
        return self.errors.get("restype", self.error_class(error_class="errorlist"))

    def full_clean(self):
        if self.disabled:
            self._errors = ErrorDict()
            self.cleaned_data = {}
        else:
            super(CreateForm, self).full_clean()


class MethodSelect(forms.RadioSelect):
    option_template_name = TMPL8S + "method_option.html"


class StartForm(MultiForm):
    """
    Form that allows a user to create a new record.

    The cleaned_data provides data collected from the form in the following fields:
    :param str start_meth:   either "create" or "upload", indicating whether the user wants
                             create a new draft from scratch or start with an exisitng XML-encoded
                             uploaded document.
    :param file xmlfile:     The uploaded file that should be used as the initial draft.
    :param dict create:      A dictionary with the properties for creating a record from scratch
    :param str  create.name: A mnemonic name given to the draft by the user
    :param str  create.homepage:    the new resource's homepage as a URL.
    """

    template_name = TMPL8S + "startform.html"
    xmlfile = forms.FileField(
        widget=forms.FileInput(attrs={"class": "form-control"}), required=False
    )
    start_meth = forms.ChoiceField(
        widget=MethodSelect,
        required=True,
        choices=[
            ("create", "Create a new record from scratch"),
            ("upload", "Upload an existing XML document"),
        ],
    )

    def __init__(self, data=None, files=None, is_top=True, show_errors=None, **kwargs):
        self.create = CreateForm(data, files, is_top=False)
        if "error_class" not in kwargs:
            kwargs["error_class"] = CerrErrorList
        super(StartForm, self).__init__(
            data, files, {"create": self.create}, is_top, show_errors, **kwargs
        )

    def _clean_form(self):
        if self.cleaned_data.get("start_meth") == "upload":
            self.create.disabled = True
            if not self.files.get("xmlfile"):
                if "xmlfile" not in self._errors:
                    self._errors["xmlfile"] = CerrErrorList([], error_class="errorlist")
                self._errors["xmlfile"].append("Please select an XML file to upload")
        super(StartForm, self)._clean_form()

cerr_curate_app/createrec/forms.py
"""
a module defining Form subclasses used in the createrec page/app
"""
import pdb
import os
from collections import OrderedDict
from collections.abc import Mapping

from django import forms as djforms
from django.utils.html import conditional_escape
from django.forms.utils import ErrorDict

from cerr_curate_app.forms import MultiForm, CerrErrorList

app_name = 'createrec'

class CreateWidget(djforms.widgets.MultiWidget):
    template_name = os.path.join(app_name, 'create.html')

    def __init__(self, attrs=None):
        self.name = djforms.TextInput()
        self.homepage = djforms.TextInput()
        components = OrderedDict([
            ('name',     self.name),
            ('homepage', self.homepage)
        ])
        super(CreateWidget, self).__init__(components, attrs)

    def decompress(self, value):
        if value is None:
            value = {}
        if not isinstance(value, Mapping):
            raise TypeError("CreateWidget: value to decompress is not a dict: "+str(type(value)))
        return [value.get('name'), value.get('homepage')]

    def get_context(self, name, value, attrs):
        """
        return the context that will be passed to the widget template
        """
        context = super().get_context(name, value, attrs)
        subwidgets = context['widget']['subwidgets']
        context['widget']['subwidgets'] = {
            'name': subwidgets[0],
            'homepage': subwidgets[1]
        }
        return context
        

class CreateField(djforms.fields.MultiValueField):
    """
    A Field for collecting inputs for creating a new record

    It includes:
     * a text field for entering a mnemonic name
     * a URL field for entering the resource's landing page
     * an array of radio buttons for selecting a type
    """
    widget = CreateWidget

    def __init__(self, **kw):
        self.name = djforms.CharField(required=True)
        self.homepage = djforms.URLField()

        super(CreateField, self).__init__([self.name, self.homepage], label='', **kw)
                                          

    def compress(self, values):
        out = {}
        out['name'] = self.name.clean(values[0])
        out['homepage'] = self.name.clean(values[1])
        return out
            
    

class CreateForm(djforms.Form):
    """
    A Form for creating an initial draft of a record.

    It includes:
     * a text field for entering a mnemonic name
     * a URL field for entering the resource's landing page
     * an array of radio buttons for selecting a type
    """
    template_name = 'createrec/create.html'
    name = djforms.CharField(required=True)
    homepage = djforms.URLField(required=False)

    def __init__(self, data=None, files=None, is_top=True, show_errors=None, **kwargs):
        self.is_top = is_top
        self.show_aggregate_errors = show_errors
        self.disabled = False
        if self.show_aggregate_errors is None:
            self.show_aggregate_errors = self.is_top
        if 'error_class' not in kwargs:
            kwargs['error_class'] = CerrErrorList
        super(CreateForm, self).__init__(data, files, **kwargs)
        
    @property
    def name_errors(self):
        """
        return the errors associated with the name input
        """
        return self.errors.get("name", self.error_class(error_class="errorlist", renderer=self.renderer))
        
    @property
    def homepage_errors(self):
        """
        return the errors associated with the homepage input
        """
        return self.errors.get("homepage", self.error_class(error_class="errorlist", renderer=self.renderer))

    def full_clean(self):
        if self.disabled:
            self._errors = ErrorDict()
            self.cleaned_data = {}
        else:
            super(CreateForm, self).full_clean()

class MethodSelect(djforms.RadioSelect):
    option_template_name = 'createrec/method_option.html'

class StartForm(MultiForm):
    """
    Form that allows a user to edit a new record
    """

    template_name = 'createrec/start.html'
    xmlfile = djforms.FileField(widget=djforms.FileInput(attrs={'class': 'form-control'}), required=False)
    start_meth = djforms.ChoiceField(widget=MethodSelect, required=True, choices=[
        ('create', 'Create a new record from scratch'),
        ('upload', 'Upload an existing XML document')
    ])

    def __init__(self, data=None, files=None, is_top=True, show_errors=None, **kwargs):
        self.create = CreateForm(data, files, is_top=False)
        if 'error_class' not in kwargs:
            kwargs['error_class'] = CerrErrorList
        super(StartForm, self).__init__(data, files, {'create': self.create},
                                        is_top, show_errors, **kwargs)
        
    def _clean_form(self):
        if self.cleaned_data.get('start_meth') == 'upload':
            self.create.disabled = True
            if not self.files.get('xmlfile'):
                if 'xmlfile' not in self._errors:
                    self._errors['xmlfile'] = CerrErrorList([], error_class="errorlist",
                                                            renderer=self.renderer)
                self._errors['xmlfile'].append('Please select an XML file to upload')
        super(StartForm, self)._clean_form()

cerr_curate_app/createrec/views.py
import pdb
from collections import OrderedDict

from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .forms import StartForm

# Create your views here.
def start(request):
    """
    Present or handle the starting form for creating a record
    """
    if request.method == 'POST':
        form = StartForm(request.POST, request.FILES)
        if form.is_valid():
            id = process_create_request(form.cleaned_data, request.FILES.get('xmlfile'))
            return HttpResponseRedirect(reverse('editrec:edit', args=(id,)))

    else:
        form = StartForm()

    return render(request, 'createrec/index.html', { 'startform': form })

drafts = {}
def process_create_request(reqdata, file_submission=None):
    global drafts
    draft = OrderedDict([('identity', OrderedDict()),
                         ('content',  OrderedDict())])
    if file_submission is None or reqdata['start_meth'] == 'create':
        if reqdata['create'].get('homepage'):
            draft['content']['landingPage'] = reqdata['create'].get('homepage')
        drafts[reqdata['create']['name']] = draft
        return reqdata['create']['name']

    draft['file'] = file_submission
    drafts[file_submission.name] = draft
    return file_submission.name
    
    


def store_post_as_draft(data):
    """
    Given the create data provided by the createrec page, create and store a draft record

    :param dict data:  the POST data delivered by a submitted createrec form
    """
    missing = []

    if not data.get('start_meth'):
        missing.append('start_meth')
    if not data.get('name'):
        missing.append('name')

    if missing:
        raise MissingFormData("createrec.start: Form submission missing required keys: "+str(keys),
                              keys=missing)

    # convert and store data

def harvest_from_url(data, url):
    """
    resolve the given URL and attempt to extract metadata.  If the URL is a DOI URL, pull its DOI metadata.
    If it points to a regular web page, attempt to scrape schema.org metadata.
    """
    return data



    

cerr_curate_app/createrec/templates/createrec/create.html
<div id="id_create">
{% if form.show_aggregate_errors %}
{% if form.errors %}<div style="color: red;"><i>Please correct the errors indicated below</i></div>{% endif %}
{{ errors }}
{% endif %}
<fieldset>
  <div class="mb-3">
    <label class="form-label" for="input-name">Short mnemonic name:</label> <br/>
    {{ form.name_errors }}
    <input type="text" class="form-label" id="input-name" size="30" minlength="1"
           {% if form.name.value != None %}value="{{ form.name.value|stringformat:'s' }}"{% endif %}
           name="{{ form.name.html_name }}" />
    <div id="nameHelp" class="form-text">
      This is a short name you can use to recognize this record; it is not shared publicly.
    </div>
  </div>

  <div class="mb-3">
    <label class="form-label" for="input-homepage">Resource's Home Page URL (optional):</label> <br/>
    {{ form.homepage_errors }}
    <input type="text" class="form-label" id="input-homepage" size="80"
           {% if form.homepage.value != None %}value="{{ form.homepage.value|stringformat:'s' }}"{% endif %}
           name="{{ form.homepage.html_name }}"/>
  </div>
</fieldset>
</div>

cerr_curate_app/createrec/templates/createrec/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Create a New Record</title>
  <script src="{% static 'js/jquery.slim.min.js' %}" ></script>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'createrec/css/main.css' %}" rel="stylesheet">
  <link href="{% static 'css/cerr_curate_app/forms.css' %}" rel="stylesheet">
</head>

<body id="content">
<h1>Create or Upload a New Record</h1>

<form enctype="multipart/form-data" action="/createrec/" method="post">
{% csrf_token %}

  {{ startform }}
  <div style="margin-top: 2ex">
  <input type="submit" value="Edit new record"/>
  <div>
</form>



</body> </html>

cerr_curate_app/createrec/templates/createrec/show.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Create a New Record</title>
  <script src="{% static 'js/jquery.slim.min.js' %}" ></script>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'createrec/css/main.css' %}" rel="stylesheet">
</head>

<body id="content">
<h1>New Record Data</h1>

<strong>Method:</strong> {{ start_meth }} <br>
{% if start_meth == 'create' %}
<strong>name: </strong> {{ create.name }} <br>
<strong>home: </strong> {{ create.homepage }} <br>
{% else %}
<strong>file: </strong> <br>
<verbatim>
{{ xmlfile }}
</verbatim>
{% endif %}

{% if errors %}
Errors:
<ul>
  {% for fld,err in errors.items %}
  <li> {{ fld }}: {{ err }} </li>
  {% endfor %}
</ul>
{% endif %}

</body> </html>

cerr_curate_app/createrec/templates/createrec/start.html
  <script type="text/javascript">
  function createrec_disable_create(ev) {
      // var fs = $("#id_create fieldset")
      // console.log("flipping disable on "+fs.get(0).localName+" to "+(ev.target.value != "create"));
      $("#id_create fieldset").get(0).disabled = ev.target.value != "create";
      $("#id_xmlfile").get(0).disabled = ev.target.value == "create";
  }
  </script>

  {{ errors }}
  <div class="form-check">
    {{ form.start_meth.0 }}
  </div>
  <div style="margin-left: 1.5rem">
  {{ form.create }}
  </div>

  <div class="form-check">
    {{ form.start_meth.1 }}
  </div>
  <div style="margin-left: 1.5rem; margin-top: .125rem;">
  {{ form.xmlfile.errors }}
  {{ form.xmlfile }}
  </div>