cerr_curate_app/cerr_curate_app/urls.py
from django.urls import include, path
from django.contrib import admin

from .views.user import draft
from .views.user import ajax as user_ajax

app_name = "draft"
urlpatterns = [
    path("draft/edit/ajax_get_role", user_ajax.role_form, name="ajax_get_role"),
    path("admin/", admin.site.urls),
    path("draft/start/", draft.start, name="start"),
    path("draft/edit/<str:draft_id>", draft.EditView.as_view(), name="edit"),
]

cerr_curate_app/urls.py
from django.urls import re_path
from cerr_curate_app.views.user import views as user_cerr_views, ajax as ajax

urlpatterns = [
    re_path(r"^$", user_cerr_views.get_name, name="core_curate_index"),

]

cerr_curate_app/cerr_curate_app/forms.py
"""
A module of common form conponents used across the cerr app
"""
import pdb
import os
from collections import OrderedDict
from collections.abc import Mapping

from django import forms as djforms
from django.utils.html import conditional_escape
from django.utils.datastructures import MultiValueDict
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from django.forms.utils import ErrorList

_template_name_fields_first = 'createrec/multiform_fields_first.html'
_template_name_fields_last  = 'createrec/multiform_fields_last.html'

class MultiForm(djforms.Form):
    """
    a form composed from multiple, re-usable djforms
    """
    template_name_fields_first = _template_name_fields_first
    template_name_fields_last  = _template_name_fields_last
    template_name = _template_name_fields_first

    def __init__(self, data=None, files=None, forms=[], is_top=True, show_errors=None,
                 template=None, **kwargs):
        """
        Wrap a collection of forms into a single form

        :param data:  the data to bind to the form (as provided by HttpRequest.POST)
        :param files: the file data to bind to the form (as provided by HttpRequest.FILES)
        :param forms: the forms to wrap.  The best way to provide these is as an OrderedDict
                      as the name will be used to set a unique name for the encosed input 
                      fields, and the order will specify the order that the forms are arranged
                      on the output page.  If given as a list, the order determines the
                      arrangement, and unique names will be created from the provided prefix
                      argument.  
                      :type forms: {name, Form} or [Form] or Form
        :param bool is_top:  If True (default), this form is expected to be the top of the 
                      form hierarchy.  This is set a property that can be consulted by subclasses
                      as needed, but it also sets the default value for the show_errors property
                      to the same value.  
        :param bool show_errors:  If False, the collected errors detected on bound data will be not
                      displayed in this form (assuming the attached template supports 
                      this property); however, they will be available for display by the enclosing
                      form.  This does not affect the display of errors close to the input fields 
                      where the error was detected.  

        In addition, this constructor supports all of the parameters supported by Form; one must 
        specify them explicitly using their argument keywords.  
        """
        prefix = kwargs.get('prefix', "mf")

        if isinstance(forms, dict):
            self.forms = OrderedDict(forms)
        elif isinstance(forms, djforms.Form):
            self.forms = OrderedDict([(forms.prefix or prefix+"0", forms)])
        else:
            # assume a list; make up some names for them (based on prefix)
            self.forms = OrderedDict()
            for i, form in enumerate(forms):
                self.forms[form.prefix or prefix+str(i)] = form

        super(MultiForm, self).__init__(data, files, **kwargs)
        for fname, form in self.forms.items():
            form.prefix = fname
            if data is not None or files is not None:
                form.is_bound = data is not None or files is not None
                form.data = MultiValueDict() if data is None else data
                form.files = MultiValueDict() if files is None else files

        self.is_top = is_top
        self.show_aggregate_errors = show_errors
        if self.show_aggregate_errors is None:
            self.show_aggregate_errors = self.is_top

        if template:
            self.template_name = template

    def clean_subforms(self):
        """
        clean the data from each of the enclosed forms.  If there is a method of the form
        clean_<formname>() where <formname> is the name attached to the form at construction 
        time, it will be called; the returned value should be a compressed value for the form 
        (usually a dictionary).
        """
        for name, form in self.forms.items():
            try:
                form.full_clean()
                self.cleaned_data[name] = form.cleaned_data
                if hasattr(self, 'clean_%s' % name):
                    value = getattr(self, 'clean_%s' % name)()
                    self.cleaned_data[name] = value
            except ValidationError as ex:
                self.add_error(name, e)
            if form.errors:
                self.add_error(NON_FIELD_ERRORS, "Please correct the errors indicated below")
                    

    def _clean_form(self):
        super(MultiForm, self)._clean_form()
        self.clean_subforms()

    def get_context(self):
        context = super(MultiForm, self).get_context()
        context['subforms'] = self.forms
        return context

class CerrErrorList(ErrorList):
    template_name = 'cerr_curate_app/errorlist.html'

cerr_curate_app/cerr_curate_app/views/user/forms/edit.py
"""
a module defining Forms used to edit an existing draft record
"""
import os
from collections import OrderedDict
from collections.abc import Mapping

from django import forms as forms
from django.utils.html import conditional_escape
from django.forms.utils import ErrorDict
from cerr_curate_app.utils.fancytree.widget import FancyTreeWidget
from .base import MultiForm, CerrErrorList, ComposableForm
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from mptt.querysets import TreeQuerySet
from cerr_curate_app.components.material.models import Material
from cerr_curate_app.components.productclass.models import ProductClass

from cerr_curate_app.components.lifecycle.models import Lifecycle

from .roles import sequenceForm as sequenceForm

__all__ = ["EditForm"]

TMPL8S = "cerr_curate_app/user/forms/"
from .selectrestype import ResourceTypeChoiceField


class AudienceForm(ComposableForm):
    choices = (
        ("researchers", "researchers"),
        ("practitioners ", "practitioners "),
        ("educators", "educators"),
        ("policy makers", "policy makers"),
        ("general public", "general public"),
        ("communication specialists", "communication specialists"),
    )
    template_name = TMPL8S + "audienceform.html"
    categories = forms.MultipleChoiceField(
        choices=choices, widget=forms.CheckboxSelectMultiple, required=False
    )

    def __init__(self, data=None, files=None, is_top=True, show_errors=None, **kwargs):
        self.is_top = is_top
        self.show_aggregate_errors = show_errors
        self.disabled = False
        if self.show_aggregate_errors is None:
            self.show_aggregate_errors = self.is_top
        if "error_class" not in kwargs:
            kwargs["error_class"] = CerrErrorList
        super(AudienceForm, self).__init__(data, files, **kwargs)

    # Override get_context to add choices to context
    def get_context(self, **kwargs):
        context = super(AudienceForm, self).get_context(**kwargs)
        context["choices"] = [
            {
                "value": c[0],
                "label": c[1],
                "checked": "checked" if c[0] in self.initial["categories"] else "",
            }
            for c in self.choices
        ]
        context["input_name"] = self["categories"].html_name
        context["max_selected"] = len(self.initial["categories"]) > 1

        return context

    def full_clean(self):
        if self.disabled:
            self._errors = ErrorDict()
            self.cleaned_data = {}
        else:
            super(AudienceForm, self).full_clean()


class HomePageForm(ComposableForm):
    template_name = TMPL8S + "homepageform.html"
    url = forms.URLField(label="Home Page URL")

    def __init__(self, data=None, files=None, is_top=True, show_errors=None, **kwargs):
        self.is_top = is_top
        self.show_aggregate_errors = show_errors
        self.disabled = False
        if self.show_aggregate_errors is None:
            self.show_aggregate_errors = self.is_top
        if "error_class" not in kwargs:
            kwargs["error_class"] = CerrErrorList
        super(HomePageForm, self).__init__(data, files, **kwargs)

    @property
    def url_errors(self):
        """
        return the errors associated with the homepage input
        """
        return self.errors.get("url", self.error_class(error_class="errorlist"))

    def full_clean(self):
        if self.disabled:
            self._errors = ErrorDict()
            self.cleaned_data = {}
        else:
            super(HomePageForm, self).full_clean()


class KeywordsForm(ComposableForm):
    template_name = TMPL8S + "keywordsform.html"
    keywords = forms.CharField(widget=forms.Textarea, label="Keywords", required=False)

    def __init__(self, data=None, files=None, is_top=True, show_errors=None, **kwargs):
        self.is_top = is_top
        self.show_aggregate_errors = show_errors
        self.disabled = False
        self.initial = None
        if self.show_aggregate_errors is None:
            self.show_aggregate_errors = self.is_top
        if "error_class" not in kwargs:
            kwargs["error_class"] = CerrErrorList
        if "initial" in kwargs:
            self.initial = kwargs["initial"]
        super(KeywordsForm, self).__init__(data, files, **kwargs)

    def get_context(self, **kwargs):
        context = super(KeywordsForm, self).get_context(**kwargs)
        if self.initial:
            context["prevKeywords"] = self.initial["keywords"]
        return context

    def full_clean(self):
        if self.disabled:
            self._errors = ErrorDict()
            self.cleaned_data = {}
        else:
            super(KeywordsForm, self).full_clean()


class EditForm(MultiForm):
    """
    Form that allows a user to create a new record.

    The cleaned_data provides data collected from the form in the following fields:
    :param str homepage:   the resource's home page URL
    """

    template_name = TMPL8S + "editform.html"
    description = forms.CharField(widget=forms.Textarea, label="Description")
    pubyear = forms.CharField(widget=forms.HiddenInput, required=False)
    # recname = forms.CharField(widget=forms.HiddenInput)

    def __init__(
        self,
        data=None,
        files=None,
        resource_type="Resource",
        is_top=True,
        show_errors=None,
        initial=None,
        **kwargs
    ):

        self.resourcetype = resource_type
        initial = self._unclean_data(initial)

        self.restitle = forms.CharField(
            label="Title of " + self.resourcetype, required=True
        )
        self.publisher = forms.CharField(
            label="Publisher of " + self.resourcetype, required=True
        )
        self.homepage = HomePageForm(
            data, files, is_top=False, initial=initial.get("homepage")
        )
        self.audience = AudienceForm(
            data, files, is_top=False, initial=initial.get("audience")
        )

        self.productclass = ProductClassForm(initial=initial.get("productClass"))
        self.lifecyclephase = LifecyclePhaseForm(initial=initial.get("lifecyclePhase"))
        self.materialtype = MaterialTypeForm(initial=initial.get("materialType"))

        self.keywords = KeywordsForm(
            data, files, is_top=False, initial=initial.get("keywords")
        )

        self.roleform = RoleForm(data, files, is_top=False, initial=initial.get("role"))
        self.sequence = sequenceForm(
            data, files, is_top=False, initial=initial.get("sequence")
        )
        self.is_top = is_top
        self.show_aggregate_errors = show_errors
        if self.show_aggregate_errors is None:
            self.show_aggregate_errors = self.is_top
        if "error_class" not in kwargs:
            kwargs["error_class"] = CerrErrorList
        super(EditForm, self).__init__(
            data,
            files,
            {
                "homepage": self.homepage,
                "productClass": self.productclass,
                "audience": self.audience,
                "sequence": self.sequence,
                "role": self.roleform,
                "keywords": self.keywords,
                "materialType": self.materialtype,
                "lifecyclePhase": self.lifecyclephase,
            },
            initial=initial,
            field_order="recname title publisher pubyear description".split(),
            **kwargs
        )
        self.fields["title"] = self.restitle
        self.fields["publisher"] = self.publisher
        self.order_fields(self.field_order)

    def full_clean(self):
        super(EditForm, self).full_clean()

    def _post_clean(self):
        # flatten the fancy tree data
        for ft in "productClass materialType lifecyclePhase".split():
            if ft in self.cleaned_data:
                if (
                    isinstance(self.cleaned_data[ft], Mapping)
                    and "ft" in self.cleaned_data[ft]
                ):
                    self.cleaned_data[ft] = self.cleaned_data[ft]["ft"]

        if "homepage" in self.cleaned_data and "url" in self.cleaned_data["homepage"]:
            self.cleaned_data["homepage"] = self.cleaned_data["homepage"].get("url", "")

        if (
            "audience" in self.cleaned_data
            and "categories" in self.cleaned_data["audience"]
        ):
            self.cleaned_data["audience"] = self.cleaned_data["audience"].get(
                "categories", ""
            )

        if (
            "keywords" in self.cleaned_data
            and "keywords" in self.cleaned_data["keywords"]
        ):
            self.cleaned_data["keywords"] = self.cleaned_data["keywords"].get(
                "keywords", []
            )
        if (
            "sequence" in self.cleaned_data
            and "sequence" in self.cleaned_data["sequence"]
        ):
            self.cleaned_data["sequence"]["service"] = self.cleaned_data[
                "sequence"
            ].get("service")
            self.cleaned_data["sequence"]["database"] = self.cleaned_data[
                "sequence"
            ].get("database")
            self.cleaned_data["sequence"]["semanticasset"] = self.cleaned_data[
                "sequence"
            ].get("semanticasset")
            self.cleaned_data["sequence"]["software"] = self.cleaned_data[
                "sequence"
            ].get("software")

        if "role" in self.cleaned_data and "role" in self.cleaned_data["role"]:
            self.cleaned_data["role"] = self.cleaned_data["role"].get("role", [])

    def _unclean_data(self, data):

        if isinstance(data, Mapping):
            for ft in "productClass materialType lifecyclePhase".split():
                if ft in data:
                    data[ft] = {"ft": data[ft]}

            if "homepage" in data and isinstance(data["homepage"], str):
                data["homepage"] = {"url": data["homepage"]}

cerr_curate_app/views/user/forms.py
from django import forms


class NameForm(forms.Form):
    name = forms.CharField(label='name', max_length=100)
    address = forms.CharField(label='address', max_length=100)
    number = forms.IntegerField(label='number')
    country = forms.CharField(label='country', max_length=100)

cerr_curate_app/views/user/views.py
"""Curate registry app user views
"""

from django.http import HttpResponseRedirect
from django.shortcuts import render

from cerr_curate_app.components.cerrdata import api as cerrdata_api
from core_main_app.utils.rendering import render
from .forms import NameForm


def index(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            return HttpResponseRedirect('/curate?submitted=True')
    else:

        context = {}
        context['form'] = NameForm()
        return render(
            request,
            "cerr_curate_app/user/curate.html",
            context=context
        )


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = cerrdata_api.save_as_cerr_data(request)
            # redirect to a new URL:
            return HttpResponseRedirect('/curate?submitted=True')

    # if a GET (or any other method) we'll create a blank form
    else:

        form = NameForm()

    return render(request, 'cerr_curate_app/user/curate.html', context={'form': form})

cerr_curate_app/cerr_curate_app/templates/cerr_curate_app/user/forms/audienceform.html
<script>
    // Handle a maximum of 'limit' checkboxes selected

    var limit = 2;
    $(document).ready(function(){

        $("input[type=checkbox]").click(function(){
            areChecked=$("#div_id_audience input:checked")
            var all = $("#div_id_audience input")
            nb_checked= $("#div_id_audience input:checked").length;

            if (nb_checked<limit) {
                for (var el in all){
                    if(all[el].parentElement){
                        all[el].parentElement.classList.remove("grey");
                    }
                }
             }
            if (nb_checked == limit) {
                 for (var el in all){
                    if(!all[el].checked) {
                        if(all[el].parentElement){
                            all[el].parentElement.classList.add("grey");
                       }
                   }
                }
            }
            if (nb_checked>limit) {
                console.log('nop too many')
                this.checked=false;
            }
        });
    });
</script>


    <style>
        .title {
        font-weight: bold;
        display: inline-block;
        }

        .titleRow{
        margin-top: 1.5em;
        }

        .grey {
        color: grey;
        }

        .single-checkbox{
        margin: 0 0.5em
        }

        .contentRow{
        margin-top:-0.5em
        }


    </style>

    <div id="div_id_audience">
        <div class="titleRow">
            <p class="title"> Primary Audience </p>
            <span>(maximum 2)</span>
        </div>

        <div class="contentRow">
            {% for choice in choices %}
                <div class="form-check-inline{% if max_selected and not choice.selected %} grey{% endif %}">
                    <input type="checkbox" class="single-checkbox" name="{{input_name}}"
                           value="{{choice.value}}" {{choice.checked}}>
                    <label for="{{choice.value}}">{{choice.label}}</label><br>
                </div>
            {% endfor %}
        </div>
    </div>

cerr_curate_app/cerr_curate_app/templates/cerr_curate_app/user/forms/editform.html
{% load crispy_forms_tags %}

<html>
<script>
    var onjQueryReady = function (method) {
        if (window.jQuery) {
            method();
        }
        else {
            setTimeout(function () { onjQueryReady(method) }, 50);
        }
    };
    /**
     * Get script in param thanks to its url.
     * Use a cache to avoid getting several time the same script.
     * @param url
     * @param options
     */
    cachedScript = function (url, options) {
        // Allow user to set any option except for dataType, cache, and url
        options = $.extend(options || {}, {
            dataType: "script",
            cache: true,
            url: url
        });

        // Use $.ajax() since it is more flexible than $.getScript
        // Return the jqXHR object so we can chain callbacks
        return $.ajax(options);
    };

</script>

<div class="forms-content">
<div class="body-text">
    <div class="boldLabel">
    {{form.title|as_crispy_field }}
    {{form.publisher|as_crispy_field }}
    {{form.pubyear}}
    {{form.description|as_crispy_field }}
    </div>

    {{ errors }}
    <div class="top1 boldLabel" id="div_id_url">
        {{form.homepage}}
    </div>
        <div>
            {{form.audience}}
        </div>
        <div  class="boldLabel" id="div_id_product">

            {{form.productclass}}
        </div>
            <div class="top1 boldLabel" id="div_id_material">
                {{form.materialtype }}
            </div>
            <div class="top1 boldLabel" id="div_id_lifecycle">
                {{form.lifecyclephase }}
            </div>

        <div class="top1" id="div_id_keywords">
            {{ form.keywords }}
        </div>

    <div class="top1 boldLabel" id="div_id_role">
        {{form.sequence}}
    </div>

</div>


    <div id="canvas-left">
        <div class="fixed">

    <div class="second">
            <button class="btn btn-success btn-sm" type="submit" onclick=saveRole()><span>Save</span> <i class="fas fa-save"></i> </button>


            <button class="btn btn-warning btn-sm" type="button"><span>Undo</span><i class="fas fa-undo"></i></button>

                <button class="btn btn-danger btn-sm" type="reset"><span>Clear</span><i class="fas fa-times"></i></button>

    </div>

    <div class="third">
        <div class="helper">
            <p>Helpers</p>

        </div>
        <div>
            <details id="title_details">
                <summary>Title</summary>
                <p>A name for the access method or the thing accessed via the
             accessURL</p>

            </details>
        </div>
        <div>
            <details id="publisher_details">
                <summary>Publisher</summary>
                <p>Entity (e.g. person or organisation) responsible for making the
               resource available</p>

            </details>
        </div>
        <div>
            <details id="description_details">
                <summary>Description</summary>
                <p>An account of the nature of the resource</p>

            </details>
        </div>
        <div>
            <details id="url_details">
                <summary>Homepage URL</summary>
                <p>The URL that through which user can access the resource via
               this method</p>

            </details>
        </div>
        <div>
            <details id="audience_details">
                <summary>Primary Audience</summary>
                <p>The primary audience this resource is intended for</p>

            </details>
        </div>
        <div>
            <details id="product_details">
                <summary>Product Class</summary>
                <p>a category of product to be processed or recycled</p>

            </details>
        </div>
        <div>
            <details id="material_details">
                <summary>Material Type</summary>
                <p>a property that captures Material types vocabulary</p>

            </details>
        </div>
        <div>
            <details id="lifecycle_details">
                <summary>Lifecycle Phase</summary>
                <p>Phase in the lifecycle of a material in the circular economy</p>

            </details>
        </div>
        <div>
            <details id="keywords_details">
                <summary>Keywords</summary>
                <p>a topic, object type, or other descriptive keywords
                about the resource</p>

            </details>
        </div>
        <div>
            <details id="role_details">
                <summary>Role</summary>
                <p>A label indicating the role this date plays in the lifecycle
                of a resource</p>

            </details>
        </div>
    </div>
    </div>
</div>
</div></html>

cerr_curate_app/cerr_curate_app/templates/cerr_curate_app/user/forms/homepageform.html
{% load crispy_forms_tags %}
<div id="homepage_form">
{% if form.show_aggregate_errors %}
{% if form.errors %}<div style="color: red;"><i>Please correct the errors indicated below</i></div>{% endif %}
{{ errors }}
{% endif %}
    <div class="url">
        <label class="form-label" for="create-homepage">Resource's Home Page URL*:</label> <br/>
    {{ form.url_errors }}
    <input type="text" class="urlinput form-control" id="edit-homepage" size="80"
           {% if form.url.value != None %}value="{{ form.url.value|stringformat:'s' }}"{% endif %}
           name="{{ form.url.html_name }}"/> &nbsp; &nbsp;<br />
        <button type ="button">Auto-Fill</button> Press this to autofill the form <br />
    </div>
</div>

cerr_curate_app/cerr_curate_app/templates/cerr_curate_app/user/forms/keywordsform.html
<html>

    <head>
        {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/cerr_curate_app/user/forms/css/keywordsform.css' %}">
    </head>

    <body>
        <div id="keyword_form">
            {% if form.show_aggregate_errors %}
            {% if form.errors %}
            <div style="color: red;"><i>Please correct the errors indicated below</i></div>
            {% endif %}
            {{ errors }}
            {% endif %}
            <div class="keywords titleRow" id="keywords-list">
                <p class="title">Keywords</p>

                <div id="keywordBox">
                    <ul id="dynamic-list"></ul>
                    <input type="hidden" name="keywords-keywords" id="id_keywords" value="{{prevKeywords}}">
                    <input type="text" id="candidate" placeholder="Enter keyword here..."/>
                    <button type="button" class="btn btn-primary btn-keyword" onclick="addItem()">Add</button>
                </div>
            </div>
        </div>
    </body>
</html>

cerr_curate_app/cerr_curate_app/templates/cerr_curate_app/user/forms/roleform.html
<!-- <form id="empty-layer-uploader" method="post" enctype="multipart/form-data"> -->
        <div id="form_empty_layer">
<!--      <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}"> -->
            {{ form.errors }}
            {{ form.non_field_errors }}
            {% if errormsgs %}
              {% for value in errormsgs %}
                </p>  {{ value }} </p>
              {% endfor %}
            {% endif %}
        {% for error in form_empty_layer.non_field_errors %}
              {{ error }} </br>
            {% endfor %}
            </br>
            {% for field in form_empty_layer.visible_fields %}
              {{ field }} </br>
            {% endfor %}
        </div>
        </br>
<!-- </form> -->

cerr_curate_app/cerr_curate_app/templates/cerr_curate_app/user/forms/serviceApiForm.html
<div id="url_form">
{% if form.show_aggregate_errors %}
{% if form.errors %}<div style="color: red;"><i>Please correct the errors indicated below</i></div>{% endif %}
{{ errors }}
{% endif %}
    <div class="url">
        <label class="form-label" for="create-homepage">Resource's Home Page URL (optional):</label> <br/>
    {{ form.homepage_errors }}
    <input type="text" class="" id="create-homepage" size="80"
           {% if form.homepage.value != None %}value="{{ form.homepage.value|stringformat:'s' }}"{% endif %}
           name="{{ form.homepage.html_name }}"/> &nbsp; &nbsp;</br>
        <button type ="button">Auto-Fill</button> Press this to autofill the form </br>
    </div>
</div>
{{ data.homepage }}